export const unionTypesMap = {
  passport: {
    types: [
      'passportSerialNum',
      'passportReleaseDate',
      'passportReleaseUnit',
      'passportReleaseUnitId',
    ],
    group: 'personal',
  },
  employer: {
    types: [
      'jobEmployerTitle',
      'jobEmployerItn',
      'jobEmployerAddress',
      'jobEmployerPhone',
      'jobEmployerManagersPhone',
      'jobEmployerAccountantsPhone',
      'jobTitle',
    ],
    group: 'jobs',
  },
  income: {
    types: ['jobIncomeSum', 'jobIncomeDate'],
    group: 'jobs',
  },
  driverLicense: {
    types: [
      'driversLicenseNum',
      'driversLicenseReleaseDate',
      'driversLicenseCategory',
    ],
    group: 'vehicles',
  },
  vehicle: {
    types: [
      'vehicleNum',
      'vehicleNumOutdated',
      'vehicleVin',
      'vehicleRelatedPersons',
      'vehicleBrandModel',
      'vehicleBrand',
      'vehicleModel',
      'vehicleColor',
      'vehicleReleaseYear',
      'vehicleRegistrationDate',
      'vehicleDeregistrationDate',
      'vehicleRegistrationCertificateNum',
      'vehiclePassport',
      'vehicleInsuranceAgent',
      'vehicleInsuranceNum',
      'vehicleRestriction',
      'vehicleOwnerFullname',
    ],
    group: 'vehicles',
  },
  movement: {
    types: [
      'movementDate',
      'movementAdditional',
      'movementType',
      'movementFrom',
      'movementTo',
      'movementVehicleNum',
      'movementDirection',
      'movementIsAeroflot',
    ],
    group: 'movements',
  },
  debt: {
    types: [
      'executiveProcedureInitiatorOsp',
      'executiveProcedureBaseIp',
      'executiveProcedureDebt',
      'executiveProcedureNumber',
      'executiveProcedureOffenseType',
      'executiveProcedureResolution',
      'executiveProcedurePunishment',
      'executiveProcedureDate',
    ],
    group: 'negative',
  },
  criminal: {
    types: [
      'criminalArticle',
      'criminalPart',
      'criminalPoint',
      'criminalArticleContent',
      'criminalDate',
      'criminalYear',
      'criminalDateInitiation',
      'criminalNumber',
      'criminalNote',
    ],
    group: 'negative',
  },
  wanted: {
    types: [
      'wantedDateStart',
      'wantedFable',
      'wantedBasis',
      'wantedSearchType',
      'wantedSearchCategory',
      'wantedPreventiveMeasure',
      'wantedSearchInitiator',
      'wantedDateStartCriminal',
      'wantedDateEndCriminal',
      'wantedDateTerminationSearch',
      'wantedArmed',
      'wantedPreviouslyJudged',
      'wantedNote',
    ],
    group: 'negative',
  },
}
